name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.3.6 # This is the action
              with:
                  heroku_api_key: ${{secrets.HEROKU_SECRET}}
                  heroku_app_name: 'jiffix' #Must be unique in Heroku
                  heroku_email: 'emmanuelloluwatobi@gmail.com'
