name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.3.6
              with:
                  heroku_api_key: ${{secrets.HEROKU_SECRET}}
                  heroku_app_name: 'jiffix' 
                  heroku_email: 'emmanuelloluwatobi@gmail.com'
on
   pull_request:
      branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - run: jest
